name: Make Slide (Docker)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # ğŸ³ Container jÃ¡ com PlantUML + Graphviz + Java
    container:
      image: plantuml/plantuml:latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Ruby and Asciidoctor
        run: |
          apt-get update -qq
          apt-get install -y ruby ruby-bundler ruby-dev build-essential
          gem install bundler
          gem install asciidoctor-revealjs asciidoctor-diagram

      - name: Build slides
        run: |
          bundle exec asciidoctor-revealjs \
            -r asciidoctor-diagram \
            --attribute slides \
            --attribute diagram-format=svg \
            -o build/site/index.html src/slides/asciidoc/index.adoc

      - name: Upload slides as artifact
        uses: actions/upload-artifact@v4
        with:
          name: slides
          path: build/site/
